### ISSUE TITLE
Weird characters

### ISSUE THREAD

**Issue by julianaus** [davepwsmith/zotpick-applescript#11]
Hi David,

thank you for the script. I use the whole setup suggested and I am very happy with it. One thing came up, which I cannot explain: Around every second reference key is printed with weird characters after the "@". For instance, it should print `@Fink.Anderson_2015`but prints `@Ï⁄~∆.Anderson_2015`.  Do you have an idea what could cause this? 

I use the latest version of the [Script's app file in Scrivener][https://github.com/davepwsmith/zotpick-applescript/blob/master/zotpick-pandoc%20for%20Scrivener.app.zip]. 
Best,
Julian

**Comment by Jmuccigr** [comment]
@julianaus, I'm not actively using this particular script, so I don't know whether this is a common problem. Could you post details about your OS and Scrivener versions? Also, maybe a screen shot of the problem?

**Comment by julianaus** [comment]
Hi @Jmuccigr, I use Mac OS 10.12.3, Scrivener 2.8.1.2. 
Here is a screenshot (I highlighted the part inserted by the script): 
<img width="995" alt="screen shot 2017-03-01 at 15 35 12" src="https://cloud.githubusercontent.com/assets/5329532/23464249/b70ad024-fe94-11e6-928d-ec6cf5040741.png">

**Comment by Jmuccigr** [comment]
I just increased the delay time between characters in the version in my repository: https://github.com/Jmuccigr/zotpick-applescript

Try it out and see what happens. I don't have any problem on my system, but I'm using ElCap, not Sierra.

**Comment by julianaus** [comment]
Thanks, this improved something, but didn't solve it. 
Now, it prints `@FInk.Anderson_2015` (with two uppercase letters after the "@"), and other references are still scrambled, e.g. `@˘¨~ch.Schmidt_2005`, which should be `@Münch.Schmidt_2005`.  Can you increase the delay time a little more?

**Comment by Jmuccigr** [comment]
@julian, it might be easiest if you play with the delay yourself. Then we can avoid a lot of back and forth. Just change the delay (start with something big and decrease it until you get errors) and save the script as an application. Can you do that? If not, I'll come up with something.

**Comment by julianaus** [comment]
Thanks for the hint. A delay of 0.009 seems to do the job. I am still testing but it has been working fine with around two dozen insertions.

**Comment by Jmuccigr** [comment]
OK, I just made it 0.01 for some extra room. Still quite fast.

Get the new version from my repo and if it works for you, I'll push it here as well.

**Comment by julianaus** [comment]
Thanks, @Jmuccigr. It works fine with your new version.

**Comment by Jmuccigr** [comment]
OK, my minor changes are now merged.
