### ISSUE TITLE
Zotpick Scannable Cite adds awkward dots

### ISSUE THREAD

**Issue by vtcarlino** [davepwsmith/zotpick-applescript#14]
Hi,
Since the Zotero 5 update, Zotpick puts dots into Scannable-cite IDs instead of blank spaces where there's no data to display (e.g. page number). Here's an example: `{ | Latour, 2007 |. |. | Zu:966903:CTRBUMIB }`

As a result, I get this output at the export: (Latour, 2007, p. ..)

Is there a way to replace the dots with blanks? This way, the output won't display the "p." abbreviation but simply (Latour, 2007) as it used to do.

Thanks,

Vincent

**Comment by Jmuccigr** [comment]
Are you sure the field are completely blank? But this sounds like it might be a bug in Zotero or BBT. Can you check on that?

**Comment by vtcarlino** [comment]
Yes, the fields are blank but for some reason some dots are inserted. I opened an [issue on BBT Github page](https://github.com/retorquere/zotero-better-bibtex/issues/932) and after a few checks  with its developer, I can confirm that it's not a bug from BBT. The export is fine when I don't use zotpick.

Any idea?

**Comment by retorquere** [comment]
We've tested that when the url http://localhost:23119/better-bibtex/cayw?format=scannable cite is called up on his system, the results without the periods is result. The periods must be inserted either by zotpick (but tbh, looking at the applescript again, it seems unlikely), or scrivener is doing some kind of autocorrect. The latter could be tested by typing (not pasting) the correct reference into scrivener.

**Comment by Jmuccigr** [comment]
It's not the script, I don't think. It should just be typing what it gets from BBT.

@vtcarlino Is there any chance you've got two spaces set to autocorrect to a period?

BTW, on my Mac I'm not even getting any result from BBT when I set the format to scannable-cite. pandoc and mmd formats are fine.

EDIT: While Zotero was not responding, I submitted this BBT error report: AUGQAZME

**Comment by retorquere** [comment]
Perhaps the scannable cite plugin is not installed. I don't currently test for presence, I'll see whether I can report when it's not installed.

**Comment by retorquere** [comment]
The double space I can prevent.

**Comment by Jmuccigr** [comment]
No, I didn't have the plug-in. That was kind of useful info. :-)

Here's the output now:

```
{ | Muccigrosso, 2003 |  |  | zu:493397:AHZTVV9H }
```

Definitely has two spaces. And no, I don't get the period. I'm guessing auto-correct.

**Comment by vtcarlino** [comment]
Oh my god you're right, that was macOS autocorrect!

**Comment by retorquere** [comment]
I'll remove the double space and just report nicely if scannable cite isn't installed.

**Comment by retorquere** [comment]
I used to generate the scannable cite myself, but the label generation (which is inessential but people are pretty attached to it) process is... special and I grew tired of chasing the changes, so now I just have scannable cite itself generate the label.

**Comment by retorquere** [comment]
(btw from my POV this issue can be closed and we'll track the double-space removal in the existing BBT issue)
