### ISSUE TITLE
Zotero Integration Error with Pandoc

### ISSUE THREAD

**Issue by balandinodidonato** [davepwsmith/zotpick-applescript#15]
When I launch`zotpick-pandoc.app` I get the following error: 
> Zotero Integration Error
> Zotero experienced an error updating your document.
> documentPromise is undefined

### System:
Zotero v 5.0.47
OS: macOS High Sierra v 10.13.4

**Comment by Jmuccigr** [comment]
Sounds like it might be a Zotero issue. Are you having other problems there? Perhaps a reboot of Zotero or your system?

Otherwise, more info about your set up would help.

**Comment by tcollyer** [comment]
I am having the same issue today, with Zotero 5.0.47 and OS: macOS High Sierra v 10.13.5

Edit: D'oh, just needed up update BetterBibtex. Simply fixed!
