### ISSUE TITLE
not working with zotero 5.0.48

### ISSUE THREAD

**Issue by hugh1li** [davepwsmith/zotpick-applescript#16]
Thanks for such a tool. However, when I download the app, and CMD + Y in scrivener, the red box does not show up. Any suggestions? 
<img width="411" alt="image" src="https://user-images.githubusercontent.com/6027595/41013174-c67a7476-6912-11e8-9d3f-3647da58c31b.png">

**Comment by Jmuccigr** [comment]
Is Zotero running when you get this error?

**Comment by hugh1li** [comment]
Yes, Zotero 5 is definitely running.

**Comment by Jmuccigr** [comment]
Do you have Better BibTex installed in Zotero?

**Comment by hugh1li** [comment]
Yes. I basically follow your workflow (http://davepwsmith.github.io/academic-scrivener-howto/).

**Comment by Jmuccigr** [comment]
What happens if you run this on the command line: 

`/usr/bin/curl 'http://localhost:23119/better-bibtex/cayw?probe=probe' 2>/dev/null`

That's the command that the script uses to make sure that Zotero is running with BBT.

**Comment by hugh1li** [comment]
<img width="379" alt="image" src="https://user-images.githubusercontent.com/6027595/41051997-a0aa3c18-6985-11e8-984d-f4284feaa3a3.png">

**Comment by Jmuccigr** [comment]
Whoops, get rid of the exit bit. (Edited the original)

**Comment by hugh1li** [comment]
Kk. nothing returns in the terminal.

**Comment by hugh1li** [comment]
Just making sure, when it says zotero, if I open the Mac standalone zotero 5 app, that is the required zotero, right?

**Comment by Jmuccigr** [comment]
Yes, the standalone app. Something is goofy if the command line doesn't return "ready".

If it returns nothing (just the command prompt), it means that Zotero isn't running (on my computer).

Delete the part from the "2" to the end and see what error you get.

**Comment by hugh1li** [comment]
curl: (6) Could not resolve host: localhost

Seems like some proxy issues? I am pretty sure I don't use any proxy

**Comment by Jmuccigr** [comment]
Hmmm, not sure why that's happening. Could be something with your DNS settings. (Do you have a local hosts file?) Try this instead:

`/usr/bin/curl 'http://127.0.0.1:23119/better-bibtex/cayw?probe=probe'`

**Comment by hugh1li** [comment]
This line of command return **'ready'**. But still CMD + Y does not work. I did not have anything inside my host. Something exists in the DNS. I guess that's configurations from my working university network.

<img width="599" alt="image" src="https://user-images.githubusercontent.com/6027595/41056813-588bf4f4-6993-11e8-81ba-a639fd212d77.png">

**Comment by Jmuccigr** [comment]
OK, I changed the script to use 127.0.0.1 instead of localhost. So try the version I just posted.

**Comment by hugh1li** [comment]
Not working (the previous command already returns ready!?). BTW, I am using the latest Mac OS High Sierra 10.13.5.

**Comment by Jmuccigr** [comment]
The command with 127.0.0.1 works for you, right? That is, it returns ready instead of the error you got with the version that had local host.

The version of the script (the zipped .app file) I just put on GitHub uses 127.0.0.1 instead of localhost, so I was hoping that would do it. You're saying it doesn't, right?

**Comment by hugh1li** [comment]
that's correct.

**Comment by Jmuccigr** [comment]
Hmmm, I'm on 10.13.4. If you just double-click on the app directly, what happens? I wonder if you have to tell the system to trust it.

**Comment by hugh1li** [comment]
Same thing as you CMD + Y in scrivener
<img width="406" alt="image" src="https://user-images.githubusercontent.com/6027595/41057818-1f129d7e-6996-11e8-9d55-d77e314d5b06.png">

**Comment by Jmuccigr** [comment]
OK, I'm an idiot and pushed the wrong file. Try it now, and sorry.

**Comment by hugh1li** [comment]
YES!!! The app works now. Thank you so much for your help! I truly appreciate it!

**Comment by Jmuccigr** [comment]
NP. Sorry again about that last goof-up.

This is probably a good change to implement in any case. Happy citing!
