### ISSUE TITLE
No chooser window shown

### ISSUE THREAD

**Issue by caw** [davepwsmith/zotpick-applescript#2]
Hi

Running the pandoc applescript (thanks for all the work!) but no window pops up. The app runs briefly (I can see it's name in the menu bar) and then returns immediately straight to scrivener.
A direct call to http://localhost:23119/better-bibtex/cayw?probe=probe returns 'ready'
How best to give you useful information?

**Comment by caw** [comment]
Ahhh - so it does work for me with stand alone Zotero, but not when Zotero runs within Firefox. Is that the expected behaviour?

Great environment scrivener + markdown + pandoc + zotero!

**Comment by davepwsmith** [comment]
I think there are known issues with better bibtex and the firefox plugin, so this one is out of my control I'm afraid.
