### ISSUE TITLE
Floating window in full screen?

### ISSUE THREAD

**Issue by ymshulman** [davepwsmith/zotpick-applescript#20]
Hi!

Thanks again for your work on this - it's been beyond helpful to have this functionality in Scrivener. 
I was wondering if there was something I could tweak to make the picker float above full-screen apps. As it currently stands, invoking the picker from full-screen Scrivener kicks me out of the app to another desktop (Mac), and it would be helpful if I could change that behavior. 

I'd appreciate any input on this!

**Comment by Jmuccigr** [comment]
Thanks! Glad you find it useful.

The picker functionality is entirely BetterBibTeX's. The scripts here just invoke it.

**Comment by ymshulman** [comment]
Ah okay - thanks for your reply!
