### ISSUE TITLE
Can only open the applet once before having to restart it

### ISSUE THREAD

**Issue by emmawinston** [davepwsmith/zotpick-applescript#3]
Hi, 

I'm attempting to use your suggested Scrivener + Zotero + zotpick + Marked workflow, but am struggling with the applet. When I first hit cmd + y it pops up and works perfectly, but if I want to use it again I have to force quit the applet otherwise nothing happens when I hit cmd + y a second time. Is there any way I can find out what's causing this?

**Comment by davepwsmith** [comment]
My mac was stolen last week in a burglary and I'm not planning to replace it, so troubleshooting this is going to be tricky for me. Which of the three scripts specifically are you using? And what point do you get to -- can you insert a citation?

**Comment by davepwsmith** [comment]
And are you using standalone zotero or the  Firefox plugin version?

**Comment by emmawinston** [comment]
Hi,

Really sorry to hear this - no worries if it's too much trouble, I can use an alternative workflow if needs be.

I'm using the pandoc version, and standalone Zotero. 

I can insert a citation, but the issue is that after one citation is inserted the applet crashes and I can't insert any more - if I check the script in the dock at that point it's marked as 'not responding' and can only be fixed by forced quitting. So I have to force quit and restart the applet between inserting each citation.

**Comment by davepwsmith** [comment]
I've just updated the scripts, could you try them now? You'll have to compile them to 'applications' yourself as I have no mac to test on, but there are instructions in the repo.

**Comment by emmawinston** [comment]
This seems to have resolved it - just inserted multiple citations with no issue. Thank you!

**Comment by davepwsmith** [comment]
Closed by a00c8931
