### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by nacht-falter** [davepwsmith/zotpick-applescript#30]
Hi,

thank you for this nifty little piece of software! Is there by any chance a way of changing the output of the page number to "S. 123" instead of "p. 123"? I'm writing in German, and S. ist short for "Seite" ("page" in German) and so far I have to manually change "p." to "S." everytime I add a citation. I know it's not a big deal, but is there maybe an easy fix for this?

**Comment by Jmuccigr** [comment]
Which app are you running and where is the page number showing up? Classic view?

But that's all down to Zotero or Better-BibTeX anyway. The app doesn't do anything but type the string it receives. Is your system in German?

**Comment by nacht-falter** [comment]
Hi,
my system is in English (and I would like to keep it that way) but Zotero is set to German. I'm using Typora with the Zotpick.pandoc applescript version. When I run the script via shorcut the red input bar shows up. When I pick an item and type a number it adds "p." before the number: "Author, year, p. 123" (see screenshot below), but I would like it to look like "Author, year, S. 123"
<img width="816" alt="Screen Shot 2021-04-14 at 22 16 31" src="https://user-images.githubusercontent.com/81268159/114773957-f6a6f680-9d6f-11eb-9cd3-2ae234a6255a.png">

I found a workaround though: I'm now using the text replacement function of macOS to automatically turn "p." into "S." once the script has typed it into Typora. So far that works pretty well. I just hope it doesn't cause any problems.

**Comment by Jmuccigr** [comment]
Yeah, my system is also in English and I tried changing Zotero's language and the export language, but they did nothing. This is not something we can easily do here. The text is coming from Better-Bibtex, so you need to ask [over there](https://github.com/retorquere/zotero-better-bibtex).

I'd be curious to know what the resolution is, if any.

**Comment by nacht-falter** [comment]
Ok, thanks. I might do that at some point. But actually my workaround works really well so far. So I'll close this.
