### ISSUE TITLE
Zotpick in Scrivener crashing

### ISSUE THREAD

**Issue by geraldaungst** [davepwsmith/zotpick-applescript#32]
Starting today, Zotpick is crashing when I try to add a citation in Scrivener. I suspect it may be related to the latest beta version of macOS 12.5 (21G5063a) since that is the only significant change since the last time I used it successfully.

The sequence to replicate on my system is as follows:
1. Command-Y to call up Zotpick.
2. Choose any Zotero item.
3. Zotpick types the left brace and a space, then the script halts with the following error message:
> System Events got an error: Connection is invalid. (-609)

I am using Zotero 6.0.9 and Scrivener 3.2.3. All Zotero addons are up to date. I can provide additional info if it would be helpful.

**Comment by Jmuccigr** [comment]
This is working for me under Catalina. I'd suggest waiting to see what happens with a non-beta version of the OS, especially if it was working with the previous release.

**Comment by geraldaungst** [comment]
Update: Zotpick is now working properly on Ventura (macOS 13.0 public beta) so I suspect it is something they did in the latest version of macOS 12.5. I'm closing this since it seems to be an OS problem as opposed to something in Zotpick.
