### ISSUE TITLE
Not assigning appName correctly when run as application from Scrivener

### ISSUE THREAD

**Issue by matthewlehew** [davepwsmith/zotpick-applescript#6]
I discovered this script and the [Scrivener-Pandoc-Marked workflow](http://davepwsmith.github.io/academic-scrivener-howto/) today and am very excited about it. However, I'm having trouble getting zotpick-pandoc to work. I don't know much about AppleScript, so I don't know if this is an issue brought on by macOS Sierra (I'm running build 16A239m).

Anyway, it looks like the issue is with line 3, and `appName` is being assigned the script itself (I'm running it as an application and launching with Command-Y in Scrivener, per the instructions. After selecting the source in the Zotero selector, I can see zotpick-pandoc briefly flash as the active app name in the upper left before Zotero is the active window and no change has occurred in Scrivener.

**Notes:**
- Adding `display dialog "appName is: " & appName` confirms that zotpick-pandoc is being assigned to `appName`. 
- If zotpick-pandoc is being launched for the first time from Scrivener and the confirmation dialog appears asking if you want to launch the app, Scrivener will be assigned to `appName`. However, on subsequent launches, `appName` will be zotpick-pandoc.
- Altering the script to hardcode "Scrivener" as `appName` causes it to execute without problems.

**Suggested Fix:**
- If an alternate solution to isolate the frontmost application immediately prior to the script launch can't be found, I suggest hardcoding "Scrivener" as `appName` and changing the documentation to instruct the user on how to change it for their purposes.

**Comment by davepwsmith** [comment]
Hi Matthew,

Preface: I no longer use or own a Mac after mine was stolen last year, so I am unable personally to test these scripts.

The script was originally hard-coded to use Scrivener. Early last month, @Jmuccigr modified it to work for any application and submitted a pull request, which I accepted. It seems that this either doesn't work with the upcoming OSX release, or possible doesn't work reliably in general.

@Jmuccigr @emmawinston would you be able to test the newer versions of the scripts on OSX Yosemite and confirm that they work as they are supposed to.

@matthewlehew If you download the [previous release](https://github.com/davepwsmith/zotpick-applescript/releases/tag/0.4) of the script Scrivener is hard-coded into the script. 

I would prefer to find a solution which allows the use of any application though.

@Jmuccigr Would you be interested in maintaining these applets?

**Comment by davepwsmith** [comment]
Just a thought: would a simple solution to this be to send zotpick-pandoc/mmd/scannable to the back before getting the frontmost application?

**Comment by Jmuccigr** [comment]
@davepwsmith, I suppose it makes sense for you to hand this over, huh? :-) I can do it, though I don't know how you handle that in GitHub.

As to the problem, @matthewlehew, how are you launching the script? I do it one of two ways, both of which are working for me in El Capitan:
1. Assign the script to a key combo (in my case, using Spark).
2. Run the script from the system script menu.

**Comment by matthewlehew** [comment]
@davepwsmith Hate to hear your Mac was stolen! That's awful. For now, I'm using the hard-coded version and it's working perfectly.

@Jmuccigr I save the script as an application [as detailed here](https://github.com/davepwsmith/zotpick-applescript/tree/master/Saving%20Applescripts%20as%20Applications), save it to ~/Library/Scripts/Scrivener/zotpick-pandoc, and assign it to the preference option that's tied to ⌘Y in Scrivener preferences (see pic, near bottom). 

![screen shot 2016-07-15 at 1 31 27 am](https://cloud.githubusercontent.com/assets/4981740/16864577/f2aae07e-4a2b-11e6-97ce-f97b1e85cd74.png)

**Comment by Jmuccigr** [comment]
Yeah, that definitely doesn't work for me in El Captian either. I suspect the problem comes from the way Scrivener evokes the app (note that it needs the script to be an app and isn't just running it as a script). Again, if you attach a key command to the script, it works fine, just not via Scrivener's built-in method. Likely we'd need a different version for Scrivener itself. I'll try to play with it a bit.

**Comment by matthewlehew** [comment]
So the quick fix in the short term, if one wants to use the built-in Scrivener command, may be to add the existing hardcoded script as an option if a separate one would have to be made anyway. 

I've made a [wishlist request on Scrivener's forums](http://www.literatureandlatte.com/forum/viewtopic.php?f=4&t=34990) to allow for launching an AppleScript from the command.

**Comment by EJFuchs** [comment]
Hi,

 I have tried this on Sierra and it doesn't work either from Scrivener.  I followed the steps and saved the panda script as an app and assigned it to the reference manager. When Command-Y is clicked zotero chooser pops up correctly and lets me choose a reference, but it won't insert it into my text.
My work around was to copy the script as an automator workflow ("Run Script") and assign it a shortcut in the services menu. This way works well.

**Comment by mrlyingman** [comment]
One thing you might be able to do is to install Virtualbox on your PC and install el capitan or Sierra on it. I'm really not a programmer, so if I could, I would, but I can't!

**Comment by emmawinston** [comment]
Not sure if this is helpful or actively unhelpful but after an upgrade to Sierra I have seen no change in functionality. Am I missing something?

**Comment by mrlyingman** [comment]
I'm on el capitan and it's not working.

**Comment by davepwsmith** [comment]
Hi all, I'm sorry that you're having this issue, but I won't be able to look at this. I have not had a Mac for over a year, nor a need for this functionality. I'm happy to have over maintenance of this tool to anyone who will take it on, it's extremely simple. I would suggest that somebody look at sending the script to the back before getting the frontmost window and pasting into it?

**Comment by EJFuchs** [comment]
I have been on Sierra for a while and still does not work for me.
