### ISSUE TITLE
citation not inserting into Scrivener 

### ISSUE THREAD

**Issue by BarnabasAspray** [davepwsmith/zotpick-applescript#7]
Hi, thanks very much for making this zotpick-pandoc applet. I am having a small difficulty, however.

The picker loads correctly and I can select entries, but when I press 'enter', instead of inserting the citation into Scrivener, the focus reverts to Zotero and nothing appears in Scrivener. Has this ever happened to you and is there a quick/easy way to fix it? It seems to be 95% working apart from this very last step. 

Any help you can offer would be greatly appreciated. Thanks!

**Comment by eden13** [comment]
Same exact thing happens to me. I cannot find a fix and have been looking for 2 hours, but I am very much not a coder (social scientist)....

Any help would be appreciated from this end too!

**Comment by Jmuccigr** [comment]
@BarnabasAspray, how are you invoking the script and what's your set-up?

**Comment by BarnabasAspray** [comment]
pretty much exactly following the instructions on [this page](http://davepwsmith.github.io/academic-scrivener-howto/). The only exception is that I didn't set up Scrivener to be plain text or start using pandoc markdown. 

Using OS X El Capitan, 10.11.6 (15G1108)
Scrivener version 2.8 (26295)
Zotero version 4.0.29.5

Let me know if any more information would be helpful!

**Comment by Jmuccigr** [comment]
Yes, this happens to me too when I use Scrivener's built-in command, but it doesn't happen if I use the script from the script menu (with or without a hotkey you can set). I describe this a little more in issue #6. It's not hard to set up.

**Comment by Jmuccigr** [comment]
OK, I think I just fixed this by hard-coding "Scrivener" as the app name. It works for me anyway. You can either download the .applescript version, save it as an app via Script Editor, and then point Scrivener at it, or you can unzip the .app version that I posted and point Scrivener at that.
